
import ImageToggler from "@/components/ImageToggler";
import type { Metadata } from "next";
import { Bricolage_Grotesque, Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const bricolage_grotesque = Bricolage_Grotesque({
  subsets: ["latin"],
})

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${bricolage_grotesque.className} ${inter.variable} dark:bg-black bg-white antialiased`}
      >
        <Providers>
          <ImageToggler />
          {children}
        </Providers>
      </body>
    </html>
  );
}
